#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PATH=$PATH:"$(dirname "$0")/../../node_modules/.bin/"

if git-branch-is -r -q "main|^release/"; then
  echo "Skip linting staged changes on protected branch"
  exit 0
else
  lint-staged
fi
